import { ProcessAreaNode } from '../flow/ProcessAreaNode'
import { FileUploadNode } from './FileUploadNode'
import { DatabaseQueryNode } from './DatabaseQueryNode'
import {
  ColumnTypeDetectionNode,
  MissingValueNode,
  DuplicateDetectionNode,
  FilterRowsNode,
  StatisticsNode,
  AnomalyDetectionNode,
  CCSGSGAnomalyNode,
  CorrelationNode,
  DistributionNode,
} from './AnalysisNodes'
import { ReportNode, DashboardNode } from './OutputNodes'
import { TrainTestSplitNode, MLModelNode } from './MLNodes'
import { ChartNode } from './ChartNode'
import { CategoryNode } from './CategoryNode'
import {
  ChunkProcessingNode,
  LargeDatasetProfilerNode,
  MapReduceAggregationNode,
  SparkGroupByNode,
} from './BigDataNodes'
import { RouteNode, CodeSQLNode } from './UtilityNodes'
import { JoinNode } from './TransformationNodes'

/**
 * Registered outside any component to avoid React Flow re-renders.
 * Maps node `type` strings → custom React components.
 */
export const nodeTypes = {
  process_area:            ProcessAreaNode,
  category_node:           CategoryNode,
  file_upload:             FileUploadNode,
  database_query:          DatabaseQueryNode,
  column_type_detection:   ColumnTypeDetectionNode,
  missing_value:           MissingValueNode,
  duplicate_detection:     DuplicateDetectionNode,
  filter_rows:             FilterRowsNode,
  statistics:              StatisticsNode,
  anomaly_detection:       AnomalyDetectionNode,
  ccsg_sg_anomaly:         CCSGSGAnomalyNode,
  correlation:             CorrelationNode,
  distribution:            DistributionNode,
  time_series:             DistributionNode,
  chunk_processing:        ChunkProcessingNode,
  mapreduce_aggregation:   MapReduceAggregationNode,
  spark_groupby:           SparkGroupByNode,
  large_dataset_profiler:  LargeDatasetProfilerNode,
  join_node:               JoinNode,
  route_node:              RouteNode,
  code_sql:                CodeSQLNode,
  train_test_split:        TrainTestSplitNode,
  ml_model:                MLModelNode,
  bar_chart:               ChartNode,
  clustered_bar_chart:     ChartNode,
  stacked_bar_chart:       ChartNode,
  overlapping_bars:        ChartNode,
  horizontal_bar_chart:    ChartNode,
  dumbbell_chart:          ChartNode,
  diverging_bar_chart:     ChartNode,
  small_multiples:         ChartNode,
  line_chart:              ChartNode,
  area_chart:              ChartNode,
  dual_axis_chart:         ChartNode,
  stream_graph:            ChartNode,
  connected_scatter_plot:  ChartNode,
  slope_chart:             ChartNode,
  pie_chart:               ChartNode,
  donut_chart:             ChartNode,
  sunburst:                ChartNode,
  alluvial_diagram:        ChartNode,
  radar_chart:             ChartNode,
  polar_area_chart:        ChartNode,
  scatter_plot:            ChartNode,
  bubble_chart:            ChartNode,
  heatmap:                 ChartNode,
  histogram:               ChartNode,
  box_plot:                ChartNode,
  violin_plot:             ChartNode,
  beeswarm_plot:           ChartNode,
  density_heatmap:         ChartNode,
  convex_hull_chart:       ChartNode,
  word_cloud:              ChartNode,
  parallel_coordinates:    ChartNode,
  kpi_card:                ChartNode,
  kpi_grid:                ChartNode,
  stat_card:               ChartNode,
  missing_values_bar:      ChartNode,
  duplicate_rate_card:     ChartNode,
  correlation_network:     ChartNode,
  treemap:                 ChartNode,
  dot_map:                 ChartNode,
  choropleth_map:          ChartNode,
  bubble_map:              ChartNode,
  cartogram:               ChartNode,
  dorling_cartogram:       ChartNode,
  connection_map:          ChartNode,
  network_diagram:         ChartNode,
  circular_graph:          ChartNode,
  arc_diagram:             ChartNode,
  time_based_network_diagram: ChartNode,
  report:                  ReportNode,
  dashboard:               DashboardNode,
}
